(function(){
  const app=document.querySelector('#app');
  const templates={games:q('#gamesView'),access:q('#accessView'),lobby:q('#lobbyView'),round:q('#roundView'),results:q('#resultsView')};
  const CATS=[['isim','İsim','♟'],['sehir','Şehir','⌂'],['hayvan','Hayvan','♞'],['bitki','Bitki','❧'],['esya','Eşya','◆'],['marka','Marka','✦']];
  const ALPHABET='ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ'.split('');
  let session=readJson(sessionStorage.getItem('tahmisci.game.session')),currentView='',timer=null,deferredPrompt=null,lastAction={name:'',at:0},roundSaveTimer=null,expiredTickSent=false;
  const homeDraft={name:localStorage.getItem('tahmisci.game.playerName')||session?.name||'',code:''};
  function q(s,p=document){return p.querySelector(s)} function qa(s,p=document){return [...p.querySelectorAll(s)]}
  function readJson(value){try{return JSON.parse(value||'null')}catch{return null}}
  function uid(){let x=sessionStorage.getItem('tahmisci.game.player');if(!x){x=crypto.randomUUID?crypto.randomUUID():Date.now().toString(36);sessionStorage.setItem('tahmisci.game.player',x)}return x}
  function saveSession(){sessionStorage.setItem('tahmisci.game.session',JSON.stringify(session))}
  function view(name){currentView=name;app.replaceChildren(templates[name].content.cloneNode(true));document.body.dataset.view=name}
  function room(){return session?.code?GameStore.get(session.code):null}
  function me(r=room()){return r?.players.find(p=>p.id===uid())}
  function clearRoundClock(){clearInterval(timer);timer=null;expiredTickSent=false}
  function render(){clearRoundClock();const r=room();if(!r){session=null;sessionStorage.removeItem('tahmisci.game.session');return renderGames()}if(r.phase==='lobby')renderLobby(r);else if(r.phase==='round')renderRound(r);else renderResults(r)}
  function renderGames(){clearRoundClock();view('games')}
  function renderAccess(){clearRoundClock();view('access');q('#playerName').value=homeDraft.name;q('#roomCode').value=homeDraft.code;requestAnimationFrame(()=>q('#playerName')?.focus({preventScroll:true}))}
  function homeValues(){return {name:q('#playerName')?.value.trim()||'',code:q('#roomCode')?.value.trim().toUpperCase()||''}}
  function renderLobby(r){view('lobby');q('.room-code').textContent=r.code;q('#playerCount').textContent=r.players.length+'/8';q('#playerList').innerHTML=r.players.map((p,i)=>`<div class="player-row"><span class="avatar">${esc(p.name[0])}</span><b>${esc(p.name)}${p.id===r.hostId?' · Kurucu':''}</b><span class="tag ${p.ready?'good':''}">${p.ready?'Hazır':i===0?'Harf seçiyor':'Bekliyor'}</span></div>`).join('');q('#addBot').disabled=r.players.length>=8;
    const mine=me(r),isHost=r.hostId===uid();q('#turnTitle').textContent=r.letter?'Harf kilitlendi':isHost?'Bir harf seç':'Kurucu harf seçiyor';q('#turnHelp').textContent=r.letter?'Herkes hazır olduğunda tur başlayacak.':'Kullanılmış harfler tekrar seçilemez.';q('#alphabet').innerHTML=ALPHABET.map(l=>`<button data-letter="${l}" ${r.selectedLetters.includes(l)||!isHost||r.letter?'disabled':''} class="${r.pendingLetter===l?'active':''}">${l}</button>`).join('');q('#pickedLetter').textContent=r.letter||r.pendingLetter||'?';q('#confirmLetter').classList.toggle('hidden',!!r.letter);q('#confirmLetter').disabled=!r.pendingLetter||!isHost;q('#readyButton').classList.toggle('hidden',!r.letter||mine?.bot);q('#readyButton').textContent=mine?.ready?'Hazırım ✓':'Hazırım';q('#startRound').classList.toggle('hidden',!r.letter||!isHost);q('#startRound').disabled=!r.players.every(p=>p.ready)}
  function renderRound(r){view('round');expiredTickSent=false;q('#roundLetter').textContent=r.letter;q('.round-number').textContent=r.round+'. Tur';q('#answerGrid').innerHTML=CATS.map(([k,n,i])=>`<article class="answer-card"><div class="answer-head"><span aria-hidden="true">${i}</span><label for="a-${k}">${n}</label></div><input id="a-${k}" data-answer="${k}" maxlength="32" autocomplete="off" autocapitalize="characters" spellcheck="false" enterkeyhint="next" placeholder="Cevabını yaz..."></article>`).join('');syncRound(r,true);updateTimer(r);timer=setInterval(()=>{const nr=room();if(!nr||nr.phase!=='round')return render();updateTimer(nr)},250)}
  function syncRound(r,initial=false){if(currentView!=='round')return;const mine=me(r);if(!mine)return;if(initial){Object.entries(mine.answers||{}).forEach(([k,v])=>{const x=q(`[data-answer="${k}"]`);if(x)x.value=v})}qa('[data-answer]').forEach(x=>{x.closest('.answer-card')?.classList.toggle('filled',!!x.value.trim());x.disabled=!!mine.done});const finish=q('[data-action="finish"]');if(finish){finish.disabled=!!mine.done;finish.textContent=mine.done?'Tamamlandı ✓':'Tamamladım'}updateTimer(r)}
  function updateTimer(r){const left=Math.max(0,Math.ceil((r.roundEndsAt-Date.now())/1000)),m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0'),el=q('#timer');if(!el)return;el.querySelector('strong').textContent=m+':'+s;el.classList.toggle('warning',left<=15);if(left===0&&!expiredTickSent){expiredTickSent=true;GameStore.tick(r.code)}}
  function renderResults(r){view('results');q('#resultLetter').textContent=r.letter;const sorted=[...r.players].sort((a,b)=>b.score-a.score);q('#scoreRows').innerHTML=sorted.map((p,i)=>`<tr><td>${i+1}</td><td><span class="avatar">${esc(p.name[0])}</span> ${esc(p.name)}</td><td><strong>+${p.roundScore||0}</strong></td><td><strong>${p.score}</strong></td></tr>`).join('');q('#nextRound').classList.toggle('hidden',r.hostId!==uid());q('#answerReview').innerHTML='<div class="section-title"><h2>Cevaplar</h2></div><div class="review-grid">'+r.players.map(p=>`<div class="review-player"><b>${esc(p.name)}</b><div class="review-answers">${CATS.map(([k,n])=>`<span><small>${n}</small> ${esc(p.answers[k]||'—')}</span>`).join('')}</div></div>`).join('')+'</div>'}
  function answers(){return Object.fromEntries(qa('[data-answer]').map(x=>[x.dataset.answer,x.value.trim().toLocaleUpperCase('tr-TR')]))}
  function saveRoundAnswers(){if(!session?.code||currentView!=='round')return;const r=room(),mine=me(r);if(r?.phase==='round'&&!mine?.done)GameStore.answers(session.code,uid(),answers())}
  document.addEventListener('input',e=>{if(e.target.id==='playerName'){homeDraft.name=e.target.value;localStorage.setItem('tahmisci.game.playerName',homeDraft.name);return}if(e.target.id==='roomCode'){const pos=e.target.selectionStart;homeDraft.code=e.target.value.toLocaleUpperCase('tr-TR').replace(/\s/g,'');e.target.value=homeDraft.code;e.target.setSelectionRange(pos,pos);return}if(e.target.matches('[data-answer]')){const pos=e.target.selectionStart;e.target.value=e.target.value.toLocaleUpperCase('tr-TR');e.target.setSelectionRange(pos,pos);e.target.closest('.answer-card')?.classList.toggle('filled',!!e.target.value.trim());clearTimeout(roundSaveTimer);roundSaveTimer=setTimeout(saveRoundAnswers,300)}});
  document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-answer]')){e.preventDefault();const fields=qa('[data-answer]'),i=fields.indexOf(e.target);(fields[i+1]||q('[data-action="finish"]'))?.focus()}if(e.key==='Enter'&&e.target.id==='roomCode')q('[data-action="join-room"]')?.click()});
  document.addEventListener('click',async e=>{const letter=e.target.closest('[data-letter]');if(letter)return GameStore.pick(session.code,uid(),letter.dataset.letter);const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,now=Date.now();if(lastAction.name===a&&now-lastAction.at<400)return;lastAction={name:a,at:now};try{
      if(a==='games-home'){if(session?.code&&currentView!=='games'&&currentView!=='access'){GameStore.leave(session.code,uid());session=null;sessionStorage.removeItem('tahmisci.game.session')}return renderGames()}
      if(a==='open-game')return renderAccess();
      if(a==='create-room'){const {name}=homeValues();if(!name)throw Error('Kullanıcı adını yaz.');homeDraft.name=name;localStorage.setItem('tahmisci.game.playerName',name);const r=GameStore.create(name,uid());session={code:r.code,name};saveSession()}
      if(a==='join-room'){const {name,code}=homeValues();if(!name||!code)throw Error('Kullanıcı adı ve oda kodu gerekli.');homeDraft.name=name;localStorage.setItem('tahmisci.game.playerName',name);GameStore.join(code,name,uid());session={code,name};saveSession()}
      if(a==='leave-room'){GameStore.leave(session.code,uid());session=null;sessionStorage.removeItem('tahmisci.game.session');return renderGames()}
      if(a==='add-bot')GameStore.addBot(session.code);if(a==='copy-code'){await navigator.clipboard?.writeText(session.code);toast('Oda kodu kopyalandı.')}if(a==='confirm-letter')GameStore.confirm(session.code,uid());if(a==='toggle-ready')GameStore.ready(session.code,uid());if(a==='start-round')GameStore.start(session.code,uid());if(a==='finish'){clearTimeout(roundSaveTimer);GameStore.answers(session.code,uid(),answers());GameStore.done(session.code,uid())}if(a==='next-round')GameStore.next(session.code,uid());if(a==='review'){q('#answerReview').classList.toggle('hidden');return}render()
    }catch(err){lastAction={name:'',at:0};const x=q('#homeError');if(x)x.textContent=err.message;else toast(err.message)}});
  function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function toast(t){const x=q('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
  GameStore.subscribe(()=>{if(!session?.code)return;const r=room();if(!r)return renderGames();if(currentView==='round'&&r.phase==='round')syncRound(r);else render()});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;q('#installButton').classList.remove('hidden')});q('#installButton').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;q('#installButton').classList.add('hidden')}else toast('Tarayıcı menüsünden “Ana ekrana ekle”yi seçebilirsin.')});q('#soundButton').addEventListener('click',e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♪'?'♩':'♪';toast('Oyun sesi '+(e.currentTarget.textContent==='♪'?'açık':'kapalı'))});
  if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js');session?.code?render():renderGames();
})();
